-- Create scraped_products table
CREATE TABLE IF NOT EXISTS public.scraped_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id UUID REFERENCES public.nearby_stores(id) ON DELETE CASCADE,
    product_name TEXT NOT NULL,
    brand TEXT,
    price_current REAL NOT NULL,
    price_regular REAL,
    unit TEXT,
    quantity REAL,
    nutritional_claims TEXT[],
    nutrition_info JSONB,
    image_url TEXT,
    product_url TEXT,
    scraped_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Create product_search_cache table
CREATE TABLE IF NOT EXISTS public.product_search_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    geohash TEXT NOT NULL,
    query TEXT NOT NULL,
    results JSONB,
    result_count INTEGER,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    UNIQUE(geohash, query)
);

-- Enable RLS
ALTER TABLE public.scraped_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_search_cache ENABLE ROW LEVEL SECURITY;

-- Policies for scraped_products
DROP POLICY IF EXISTS "Allow public read access" ON public.scraped_products;
CREATE POLICY "Allow public read access" ON public.scraped_products
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow insert for authenticated users" ON public.scraped_products;
CREATE POLICY "Allow insert for authenticated users" ON public.scraped_products
    FOR INSERT TO authenticated WITH CHECK (true);

-- Policies for product_search_cache
DROP POLICY IF EXISTS "Allow public read access" ON public.product_search_cache;
CREATE POLICY "Allow public read access" ON public.product_search_cache
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow insert for authenticated users" ON public.product_search_cache;
CREATE POLICY "Allow insert for authenticated users" ON public.product_search_cache
    FOR INSERT TO authenticated WITH CHECK (true);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_scraped_products_store_id ON public.scraped_products(store_id);
CREATE INDEX IF NOT EXISTS idx_scraped_products_product_name ON public.scraped_products USING GIN (to_tsvector('spanish', product_name));
CREATE INDEX IF NOT EXISTS idx_product_search_cache_geohash_query ON public.product_search_cache(geohash, query);
